get http://localhost:3000/movies/

###

get http://localhost:3000/actors/
Content-Type: application/json


###
post http://localhost:3000/actor/3
Content-Type: application/json

{
  "first_name": "Keanu",
  "last_name": "Reeves",
  "known_for": "The matrix",
  "age": 57,
  "gender": "male",
  "movie_id": 2
}

###
get http://localhost:3000/movies
Content-Type: application/json


###
get http://localhost:3000/movies/1

###
patch http://localhost:3000/actors/2
Content-Type: application/json

{
 "first_name": "Keanu",
  "last_name": "Reeves",
  "known_for": "The matrix",
  "age": 57,
  "gender": "male",
  "movie_id": 2
}

###
PATCH http://localhost:3000/movies/3
Content-Type: application/json

{
    "title": "Drive",
    "year": 2011,
    "plot": "An action drama about a mysterious Hollywood stuntman and mechanic moonlighting as a getaway driver finding himself in trouble when he helps out his neighbor.",
    "director": "Nicolas Winding Refn",
    "english": true
}